# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBiTLDB27wX1ArukbimFVoDbB4Vi5_6Q
"""

nota = float(input("Digite uma nota entre zero e dez: "))
while nota > 10 or nota < 0:
  nota = float(input("Digite um valor válido"))
print("Sucesso")

numero = int(input("Por favor, digite um numero:"))
contador = 1
while contador <= 10:
  resultado = numero * contador
print(f"{numero} X {contador} = {resultado}")
contador += 1

nome = (input("Digite seu nome de usuario"))
senha = (input("Digite sua senha: "))
while nome == senha:
 print("error, tente novamente")
 nome = (input("Digite seu nome de usuario valido"))
 senha = (input("Digite sua senha valida: "))
print("sucesso")

numero = 0
while numero > 0 and numero <= 9:
 numero += 1
 print(numero)

numero = 0
while numero >= 0 and numero <= 20
 numero += 2
  print(numero)

num = int(input("digite um numero"))
contador = 1
while contador <= num:
  print(contador)
  contador += 1

num = int(input("digite um numero"))
contador = 0
while contador <= num:
  print(contador)
  contador += 2

senha = input("Digite sua senha: ")

sen = senha

while sen == senha:
  print("senha invalida")
  senha = input("Digite sua senha valida: ")
print("sucesso")