# -*- coding: utf-8 -*-
"""while2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBiTLDB27wX1ArukbimFVoDbB4Vi5_6Q
"""

nota = float(input("Digite uma nota entre zero e dez: "))
while nota > 10 or nota < 0:
  nota = float(input("Digite um valor válido"))
print("Sucesso")

numero = int(input("Por favor, digite um numero:"))
contador = 1
while contador <= 10:
  resultado = numero * contador
print(f"{numero} X {contador} = {resultado}")
contador += 1

nome = (input("Digite seu nome de usuario"))
senha = (input("Digite sua senha: "))
while nome == senha:
 print("error, tente novamente")
 nome = (input("Digite seu nome de usuario valido"))
 senha = (input("Digite sua senha valida: "))
print("sucesso")

numero = 0
while numero > 0 and numero <= 9:
 numero += 1
 print(numero)

numero = 0
while numero >= 0 and numero <= 20
 numero += 2
 print(numero)

num = int(input("digite um numero"))
contador = 1
while contador <= num:
  print(contador)
  contador += 1

num = int(input("digite um numero"))
contador = 0
while contador <= num:
  print(contador)
  contador += 2

senha = 12345
sen = input("Digite sua senha: ")
while sen != senha:
 sen = int(input("senha invalida digite novamente"))
print("Sucesso")

soma = 0
contador = 0
final = "fim"
print("Digite os números (digite 'fim' para encerrar):")
entrada = int(input("Número "))
while entrada != final:
  entrada = input("Número ")
  soma += num
  contador += 1

if contador > 0:
  media = soma / contador
  print("A media dos numeros é:", media)
else:
  print("nenhum número fornecido")

soma = 0
while True:
  num = int(input("Digite um número (0 para sair): "))
  if num == 0:
    break
  soma += num

print("A soma dos números inseridos é:", soma)

print("Digite os números (digite um número negativo para encerrar):")

maior_numero = -9999999999

numero = float(input("Número: "))

while numero >= 0:
    if numero > maior_numero:
        maior_numero = numero
    numero = float(input("Número: "))

if maior_numero != -9999999999:
    print("O maior número inserido foi:", maior_numero)
else:
    print("Nenhum número foi inserido.")

nota = float(input("Digite uma nota entre zero e dez: "))
while nota > 10 or nota < 0:
  nota = float(input("Digite um valor válido"))
print("Sucesso")

n = int(input("Quantas notas deseja inserir? "))
soma = 0
for i in range(n):
  nota = float(input(f"Digite a {i+1}ª nota: "))
  soma += nota
media = soma / n
print(f"A média das notas é {media}")

nome = (input("Digite seu nome de usuario"))
senha = (input("Digite sua senha: "))
while nome == senha:
 print("error, tente novamente")
 nome = (input("Digite seu nome de usuario valido"))
 senha = (input("Digite sua senha valida: "))
print("sucesso")

ano_contratacao = 1995
salario_inicial = 1000.00
percentual_aumento = 0.015

ano_atual = 1996
while ano_atual <= 2024:
    salario_inicial += salario_inicial * percentual_aumento
    percentual_aumento *= 2
    print("O salário atual do funcionário em", ano_atual, "é: R$", salario_inicial)
    ano_atual += 1

joao = input("Digite o nome: ")
while len(joao) <= 3:
  joao = input("Nome invalido. Digite o nome novamente: ")

idade = int(input("Digite a idade: "))
while idade < 0 or idade > 150:
  idade = int(input("Idade invalida. Digite a idade novamente: "))

salario = float(input("Digite o salário: "))
while salario <= 0:
  salario = float(input("Salário invalido. Digite o salário novamente: "))

sexo = input("Digite o sexo (f/m): ")
while sexo != 'f' and sexo != 'm':
  sexo = input("Sexo invalido. Digite o sexo novamente (f/m): ")

estado_civil = input("Digite o estado civil (s/c/v/d): ")
while estado_civil != 's' and estado_civil != 'c' and estado_civil != 'v' and estado_civil != 'd':
  estado_civil = input("Estado civil invalido. Digite o estado civil novamente (s/c/v/d): ")

print("Dados validados com sucesso!")