# -*- coding: utf-8 -*-
"""while1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mBiTLDB27wX1ArukbimFVoDbB4Vi5_6Q
"""

nota = float(input("Digite uma nota entre zero e dez: "))
while nota > 10 or nota < 0:
  nota = float(input("Digite um valor válido"))
print("Sucesso")

numero = int(input("Por favor, digite um numero:"))
contador = 1
while contador <= 10:
  resultado = numero * contador
print(f"{numero} X {contador} = {resultado}")
contador += 1

nome = (input("Digite seu nome de usuario"))
senha = (input("Digite sua senha: "))
while nome == senha:
 print("error, tente novamente")
 nome = (input("Digite seu nome de usuario valido"))
 senha = (input("Digite sua senha valida: "))
print("sucesso")

numero = 0
while numero > 0 and numero <= 9:
 numero += 1
 print(numero)

numero = 0
while numero >= 0 and numero <= 20
 numero += 2
 print(numero)

num = int(input("digite um numero"))
contador = 1
while contador <= num:
  print(contador)
  contador += 1

num = int(input("digite um numero"))
contador = 0
while contador <= num:
  print(contador)
  contador += 2

senha = 12345
sen = input("Digite sua senha: ")
while sen != senha:
 sen = int(input("senha invalida digite novamente"))
print("Sucesso")

soma = 0
contador = 0
final = "fim"
print("Digite os números (digite 'fim' para encerrar):")
entrada = int(input("Número "))
while entrada != final:
  entrada = input("Número ")
  soma += num
  contador += 1

if contador > 0:
  media = soma / contador
  print("A media dos numeros é:", media)
else:
  print("nenhum número fornecido")

soma = 0
while True:
  num = int(input("Digite um número (0 para sair): "))
  if num == 0:
    break
  soma += num

print("A soma dos números inseridos é:", soma)

print("Digite os números (digite um número negativo para encerrar):")

maior_numero = -9999999999

numero = float(input("Número: "))

while numero >= 0:
    if numero > maior_numero:
        maior_numero = numero
    numero = float(input("Número: "))

if maior_numero != -9999999999:
    print("O maior número inserido foi:", maior_numero)
else:
    print("Nenhum número foi inserido.")